### ISSUE TITLE
error while running the script

### ISSUE THREAD

**Issue by kudumi** [aquaflamingo/spotify-exporter#3]
sorry for noob question but I get his error when I try run the script "spotifyexporter"

Traceback (most recent call last):
	11: from /usr/local/bin/spotifyexporter:23:in `<main>'
	10: from /usr/local/bin/spotifyexporter:23:in `load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/exe/spotifyexporter:4:in `<top (required)>'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter.rb:3:in `<top (required)>'
	 5: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter.rb:3:in `require_relative'
	 4: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter/cli.rb:5:in `<top (required)>'
	 3: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter/cli.rb:5:in `require_relative'
	 2: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter/command/playlists.rb:5:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- playlist (LoadError)
	12: from /usr/local/bin/spotifyexporter:23:in `<main>'
	11: from /usr/local/bin/spotifyexporter:23:in `load'
	10: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/exe/spotifyexporter:4:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter.rb:3:in `<top (required)>'
	 6: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter.rb:3:in `require_relative'
	 5: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter/cli.rb:5:in `<top (required)>'
	 4: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter/cli.rb:5:in `require_relative'
	 3: from /Library/Ruby/Gems/2.6.0/gems/spotifyexporter-0.2.0/lib/spotifyexporter/command/playlists.rb:5:in `<top (required)>'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- playlist (LoadError)

**Comment by aquaflamingo** [comment]
Hi there, could you provide the exact command you ran? 

Also, it looks like you are using the system Ruby installation instead of something like `rbenv` or `rvm`. Did you install the gem to systems gems?
